micronaut:
  application:
    name: zendesk4j
  http:
    services:
      zendesk:
        url: ${:Z4J_URL} # MICRONAUT_HTTP_SERVICES_ZENDESK_URL
        email: # MICRONAUT_HTTP_SERVICES_ZENDESK_EMAIL
        token: # MICRONAUT_HTTP_SERVICES_ZENDESK_TOKEN