name: Test
on:
  pull_request:
    branches:
      - "main"
      - "[0-9]+.[0-9]+.[0-9]+" # release branches
jobs:
  build-and-analyze:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    env:
      Z4J_URL: ${{ secrets.ZENDESK_URL }}
      Z4J_TOKEN: ${{ secrets.ZENDESK_TOKEN }}
      Z4J_ADMIN_EMAIL: ${{ secrets.ZENDESK_ADMIN_EMAIL}}
      Z4J_AGENT_EMAIL: ${{ secrets.ZENDESK_AGENT_EMAIL}}
      Z4J_END_USER_EMAIL: ${{ secrets.ZENDESK_END_USER_EMAIL}}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN is required for SonarCloud to decorate PRs
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # 4.3.1
        with:
          fetch-depth: 0 # SonarCloud needs a full history to assign issues correctly
      - name: Set up JDK
        uses: graalvm/setup-graalvm@9d0e2dff13a8c69a81d72a49c9816836f963fe01
        with:
          java-version: '21'
          distribution: 'graalvm-community'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@748248ddd2a24f49513d8f472f81c3a07d4d50e1 # 4.4.4
      - name: Build and run tests
        if: ${{ github.event.pull_request.base.ref != 'main' && github.event.action != 'closed' }}
        run: ./gradlew build
      - name: Sonar Scan
        if: ${{ github.event.pull_request.base.ref == 'main' && github.event.action != 'closed' }} # Only run SonarQube on PRs to main
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonar
      - name: Upload test report
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # 4.6.2
        with:
          name: test-report
          path: build/reports/tests/test
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # 4.3.1
      - name: Set up JDK 21
        uses: graalvm/setup-graalvm@54b4f5a65c1a84b2fdfdc2078fe43df32819e4b1 # 1.4.5
        with:
          java-version: '21'
          distribution: 'graalvm-community'
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@748248ddd2a24f49513d8f472f81c3a07d4d50e1 # v4.4.4